/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * https://developerhub.ppro.com/simple-api/docs/trustly#specific-input-parameters-for-the-transaction-call.
 */
export type CoinbasePaymentMethodServiceTrustlyDetails = {
  /**
   * The country where the payer\'s bank account is located. Populated for all Trustly payments in the PMSvc API response.
   */
  country?: string;
  /**
   * IBAN of the payer. This field is optional and may not be populated for all Trustly payments in the PMSvc API response.
   */
  iban?: string;
  /**
   * Account holder names. This field is optional and may not be populated for all Trustly payments in the PMSvc API response.
   */
  accountHolder?: string;
  /**
   * Bank code of the payer\'s bank account. This field is optional and may not be populated for all Trustly payments in the PMSvc API response.
   */
  bankCode?: string;
  /**
   * Bank account number belonging to the payer. This field is optional and may not be populated for all Trustly payments in the PMSvc API response.
   */
  accountNumber?: string;
  /**
   * Partial Account Number belonging to the payer. Populated for all Trustly payments in the PMSvc API response.
   */
  partialAccountNumber?: string;
  /**
   * Bank name of the payer. Populated for all Trustly payments in the PMSvc API response.
   */
  bankName?: string;
  /**
   * Consumer Email. Populated for all Trustly payments in the PMSvc API response.
   */
  email?: string;
};
