/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { Amount } from './Amount';
import { FcmMarginWindowMeasure } from './FcmMarginWindowMeasure';

export type FCMBalanceSummary = {
  /**
   * The amount of your cash balance that is available to trade CFM futures
   */
  futuresBuyingPower?: Amount;
  /**
   * Aggregate USD maintained across your CFTC-regulated futures account and your Coinbase Inc. spot account
   */
  totalUsdBalance?: Amount;
  /**
   * USD maintained in your Coinbase Inc. spot account
   */
  cbiUsdBalance?: Amount;
  /**
   * USD maintained in your CFTC-regulated futures account. Funds held in your futures account are not available to trade spot
   */
  cfmUsdBalance?: Amount;
  /**
   * Your total balance on hold for spot and futures open orders
   */
  totalOpenOrdersHoldAmount?: Amount;
  /**
   * Your current unrealized PnL across all open positions
   */
  unrealizedPnl?: Amount;
  /**
   * Your realized PnL from the current trade date. May include profit or loss from positions you’ve closed on the current trade date
   */
  dailyRealizedPnl?: Amount;
  /**
   * Margin required to initiate futures positions. Once futures orders are placed, these funds cannot be used to trade spot. The actual amount of funds necessary to support executed futures orders will be moved to your futures account
   */
  initialMargin?: Amount;
  /**
   * Funds available to meet your anticipated margin requirement. This includes your CBI spot USD, CFM futures USD, and Futures PnL, less any holds for open spot or futures orders
   */
  availableMargin?: Amount;
  /**
   * When your available funds for collateral drop to the liquidation threshold, some or all of your futures positions will be liquidated
   */
  liquidationThreshold?: Amount;
  /**
   * Funds available in excess of the liquidation threshold, calculated as available margin minus liquidation threshold. If your liquidation buffer amount reaches 0, your futures positions and/or open orders will be liquidated as necessary
   */
  liquidationBufferAmount?: Amount;
  /**
   * Funds available in excess of the liquidation threshold expressed as a percentage. If your liquidation buffer percentage reaches 0%, your futures positions and/or open orders will be liquidated as necessary
   */
  liquidationBufferPercentage?: string;
  intradayMarginWindowMeasure?: FcmMarginWindowMeasure;
  overnightMarginWindowMeasure?: FcmMarginWindowMeasure;
};
