/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { FcmMarginWindowType } from './enums/FcmMarginWindowType';
import { MarginLevelType } from './enums/MarginLevelType';

export type FcmMarginWindowMeasure = {
  /**
   * Your margin window
   */
  marginWindowType?: FcmMarginWindowType;
  /**
   * Margin level for liquidation purposes
   */
  marginLevel?: MarginLevelType;
  /**
   * Initial margin
   */
  initialMargin?: string;
  /**
   * Maintenance margin
   */
  maintenanceMargin?: string;
  /**
   * Liquidation buffer
   */
  liquidationBuffer?: string;
  /**
   * Total Hold
   */
  totalHold?: string;
  /**
   * The amount of your cash balance that is available to trade CFM futures
   */
  futuresBuyingPower?: string;
};
