/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { Amount } from './Amount';
import { FCMSweepStatus } from './enums/FCMSweepStatus';

export type FCMSweep = {
  /**
   * The ID of the sweep request scheduled
   */
  id?: string;
  /**
   * The requested sweep amount
   */
  requestedAmount?: Amount;
  /**
   * True if the request was to sweep all available funds from your CFM futures account
   */
  shouldSweepAll?: boolean;
  /**
   * A pending sweep is a sweep that has not started processing and can be cancelled. A processing sweep is a sweep that is currently being processed and cannot be cancelled
   */
  status?: FCMSweepStatus;
  /**
   * The timestamp at which the sweep request was submitted
   */
  scheduledTime?: string;
};
