/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type FeeTier = {
  /**
   * Pricing tier for user, determined by notional (USD) volume.
   */
  pricingTier?: string;
  /**
   * Lower bound (inclusive) of pricing tier in notional volume.
   */
  usdFrom?: string;
  /**
   * Upper bound (exclusive) of pricing tier in notional volume.
   */
  usdTo?: string;
  /**
   * Taker fee rate, applied if the order takes liquidity.
   */
  takerFeeRate?: string;
  /**
   * Maker fee rate, applied if the order creates liquidity.
   */
  makerFeeRate?: string;
  /**
   * Lower bound (inclusive) of pricing tier in usd of total assets on platform.
   */
  aopFrom?: string;
  /**
   * Upper bound (exclusive) of pricing tier in usd of total assets on platform.
   */
  aopTo?: string;
  /**
   * Lower bound (inclusive) of pricing tier in notional volume for perpetual contracts.
   */
  perpsVolFrom?: string;
  /**
   * Upper bound (exclusive) of pricing tier in notional volume for perpetual contracts.
   */
  perpsVolTo?: string;
};
