/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { LiquidityIndicator } from './enums/LiquidityIndicator';
import { OrderSide } from './enums/OrderSide';

export type Fill = {
  /**
   * Unique identifier for the fill.
   */
  entryId?: string;
  /**
   * ID of the fill -- unique for all `FILL` trade_types but not unique for adjusted fills.
   */
  tradeId?: string;
  /**
   * The ID of the order.
   */
  orderId?: string;
  /**
   * Time at which this fill was completed.
   */
  tradeTime?: string;
  /**
   * String denoting what type of fill this is. Regular fills have the value `FILL`. Adjusted fills have possible values `REVERSAL`, `CORRECTION`, `SYNTHETIC`.
   */
  tradeType?: string;
  /**
   * Price the fill was posted at.
   */
  price?: string;
  /**
   * Amount of order that was transacted at this fill.
   */
  size?: string;
  /**
   * Fee amount for fill.
   */
  commission?: string;
  /**
   * The trading pair (e.g. \'BTC-USD\').
   */
  productId?: string;
  /**
   * Time at which this fill was posted.
   */
  sequenceTimestamp?: string;
  /**
   * Whether this fill gives or takes liquidity.
   */
  liquidityIndicator?: LiquidityIndicator;
  /**
   * Whether the order was placed with quote currency.
   */
  sizeInQuote?: boolean;
  /**
   * User that placed the order the fill belongs to.
   */
  userId?: string;
  /**
   * Side of order that this fill belongs to.
   */
  side?: OrderSide;
  /**
   * Portfolio that the order fill belongs to.
   */
  retailPortfolioId?: string;
};
