/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { TypesDecimal } from './TypesDecimal';
import { FeeTier } from './FeeTier';
import { GoodsAndServicesTax } from './GoodsAndServicesTax';

export type GetTransactionSummaryResponse = {
  /**
   * Total volume across assets, denoted in USD.
   */
  totalVolume: number;
  /**
   * Total fees across assets, denoted in USD.
   */
  totalFees: number;
  /**
   * Description of maker and taker rates across all applicable fee tiers.
   */
  feeTier: FeeTier;
  /**
   * Margin rate, only applicable to product_type `FUTURE`.
   */
  marginRate?: TypesDecimal;
  goodsAndServicesTax?: GoodsAndServicesTax;
  /**
   * Advanced Trade volume (non-inclusive of Pro) across assets, denoted in USD.
   */
  advancedTradeOnlyVolume?: number;
  /**
   * Advanced Trade fees (non-inclusive of Pro) across assets, denoted in USD.
   */
  advancedTradeOnlyFees?: number;
  /**
   * Coinbase Pro volume across assets, denoted in USD.
   */
  coinbaseProVolume?: number;
  /**
   * Coinbase Pro fees across assets, denoted in USD.
   */
  coinbaseProFees?: number;
  /**
   * Total balance across assets and products, which is comprised of the sum of spot, intx, and fcm, and denoted in USD.
   */
  totalBalance?: string;
};
