/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type InteracAccount = {
  accountName?: string;
  /**
   * Institution Number: a 3-digit code that tells you which bank the account belongs to — unique for every Canadian bank.
   */
  institutionNumber?: string;
  /**
   * Transit Number: a 5-digit code that tells which branch of the bank the account was created at — it is unique to each bank branch.
   */
  transitNumber?: string;
  /**
   * Account Number: a 7-digit code that identifies the account within the branch and bank entered.
   */
  accountNumber?: string;
};
