/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { MarginType } from './enums/MarginType';
import { OrderConfiguration } from './OrderConfiguration';
import { OrderSide } from './enums/OrderSide';

export type NewOrderRequest = {
  /**
   * A unique ID provided for the order (used for identification purposes). If the ID provided is not unique, the order will not be created and the order corresponding with that ID will be returned instead.
   */
  clientOrderId: string;
  /**
   * The trading pair (e.g. \'BTC-USD\').
   */
  productId: string;
  /**
   * The side of the market that the order is on (e.g. \'BUY\', \'SELL\').
   */
  side: OrderSide;
  /**
   * The configuration of the order (e.g. the order type, size, etc).
   */
  orderConfiguration: OrderConfiguration;
  /**
   * The amount of leverage for the order (default is 1.0).
   */
  leverage?: string;
  /**
   * Margin Type for this order (default is CROSS).
   */
  marginType?: MarginType;
  /**
   * **(Deprecated)** The ID of the portfolio to associate the order with. Only applicable for legacy keys. CDP keys will default to the key\'s permissioned portfolio.
   */
  retailPortfolioId?: string;
  /**
   * Preview ID for this order, to associate this order with a preview request
   */
  previewId?: string;
  /**
   * The configuration of the attached order. Only TriggerBracketGtc is eligible. Size field must be omitted as the size of the attached order is the same as that of the parent order.
   */
  attachedOrderConfiguration?: OrderConfiguration;
};
