/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { PnlConfiguration } from './PnlConfiguration';
import { PreviewFailureReason } from './enums/PreviewFailureReason';
import { PreviewWarningMsg } from './enums/PreviewWarningMsg';
import { TwapBucketMetadata } from './TwapBucketMetadata';

export type OrderPreviewResponse = {
  orderTotal: string;
  /**
   * Currency amount of the applied commission (so not the rate that was used on input)
   */
  commissionTotal: string;
  /**
   * List of potential failure reasons were this order to be submitted
   */
  errs: Array<PreviewFailureReason>;
  warning: Array<PreviewWarningMsg>;
  /**
   * The amount of the second Asset in the Trading Pair. For example, on the BTC/USD Order Book, USD is the Quote Asset.
   */
  quoteSize: string;
  /**
   * The amount of the first Asset in the Trading Pair. For example, on the BTC-USD Order Book, BTC is the Base Asset.
   */
  baseSize: string;
  bestBid: string;
  bestAsk: string;
  /**
   * Indicates whether tradable_balance should be set to the maximum amount.
   */
  isMax: boolean;
  orderMarginTotal?: string;
  /**
   * The amount of leverage for the order (default is 1.0).
   */
  leverage?: string;
  longLeverage?: string;
  shortLeverage?: string;
  slippage?: string;
  previewId?: string;
  currentLiquidationBuffer?: string;
  projectedLiquidationBuffer?: string;
  maxLeverage?: string;
  /**
   * Expected PNL of an order. This value is an estimate and does not take into account fees and slippage.
   */
  pnlConfiguration?: PnlConfiguration;
  twapBucketMetadata?: TwapBucketMetadata;
  positionNotionalLimit?: string;
};
