/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { LimitLimitFok } from './LimitLimitFok';
import { LimitLimitGtc } from './LimitLimitGtc';
import { LimitLimitGtd } from './LimitLimitGtd';
import { MarketMarketIoc } from './MarketMarketIoc';
import { SorLimitIoc } from './SorLimitIoc';
import { StopLimitStopLimitGtc } from './StopLimitStopLimitGtc';
import { StopLimitStopLimitGtd } from './StopLimitStopLimitGtd';
import { TriggerBracketGtc } from './TriggerBracketGtc';
import { TriggerBracketGtd } from './TriggerBracketGtd';
import { TwapLimitGtd } from './TwapLimitGtd';

export type OrderConfiguration = {
  /**
   * Buy or sell a specified quantity of an Asset at the current best available market price. [Read more on Market Orders](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#market-order)
   */
  marketMarketIoc?: MarketMarketIoc;
  /**
   * Buy or sell a specified quantity of an Asset at a specified price. The Order will only post to the Order Book if it will immediately Fill; any remaining quantity is canceled. [Read more on Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#limit-order)
   */
  sorLimitIoc?: SorLimitIoc;
  /**
   * Buy or sell a specified quantity of an Asset at a specified price. If posted, the Order will remain on the Order Book until canceled. [Read more on Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#limit-order)
   */
  limitLimitGtc?: LimitLimitGtc;
  /**
   * Buy or sell a specified quantity of an Asset at a specified price. If posted, the Order will remain on the Order Book until a certain time is reached or the Order is canceled. [Read more on Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#limit-order)
   */
  limitLimitGtd?: LimitLimitGtd;
  /**
   * Buy or sell a specified quantity of an Asset at a specified price. The Order will only post to the Order Book if it is to immediately and completely Fill. [Read more on Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#limit-order)
   */
  limitLimitFok?: LimitLimitFok;
  /**
   * A time-weighted average price (TWAP) order type that calculates the average price of a product to programmatically execute an order over a specified duration.
   */
  twapLimitGtd?: TwapLimitGtd;
  /**
   * Posts an Order to buy or sell a specified quantity of an Asset, but only if and when the last trade price on the Order Book equals or surpasses the Stop Price. If posted, the Order will remain on the Order Book until canceled. [Read more on Stop-Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#stop-limit-order)
   */
  stopLimitStopLimitGtc?: StopLimitStopLimitGtc;
  /**
   * Posts an Order to buy or sell a specified quantity of an Asset, but only if and when the last trade price on the Order Book equals or surpasses the Stop Price. If posted, the Order will remain on the Order Book until a certain time is reached or the Order.  [Read more on Stop-Limit Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#stop-limit-order)
   */
  stopLimitStopLimitGtd?: StopLimitStopLimitGtd;
  /**
   * A Limit Order to buy or sell a specified quantity of an Asset at a specified price, with stop limit order parameters embedded in the order. If posted, the Order will remain on the Order Book until canceled. [Read more on Bracket Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#bracket-order)
   */
  triggerBracketGtc?: TriggerBracketGtc;
  /**
   * A Limit Order to buy or sell a specified quantity of an Asset at a specified price, with stop limit order parameters embedded in the order. If posted, the Order will remain on the Order Book until a certain time is reached or the Order is canceled. [Read more on Bracket Orders.](https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/order-types#bracket-order)
   */
  triggerBracketGtd?: TriggerBracketGtd;
};
