/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { AccountType } from './enums/AccountType';
import { Amount } from './Amount';

/**
 * PortfolioPosition represents a spot position for a user in a portfolio.
 */
export type PortfolioPosition = {
  asset?: string;
  accountUuid?: string;
  totalBalanceFiat?: number;
  totalBalanceCrypto?: number;
  availableToTradeFiat?: number;
  allocation?: number;
  costBasis?: Amount;
  assetImgUrl?: string;
  isCash?: boolean;
  averageEntryPrice?: Amount;
  assetUuid?: string;
  availableToTradeCrypto?: number;
  unrealizedPnl?: number;
  availableToTransferFiat?: number;
  availableToTransferCrypto?: number;
  assetColor?: string;
  accountType?: AccountType;
};
