/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { FuturesPosition } from './FuturesPosition';
import { PerpPosition } from './PerpPosition';
import { Portfolio } from './Portfolio';
import { PortfolioBalances } from './PortfolioBalances';
import { PortfolioPosition } from './PortfolioPosition';

/**
 * PortfolioBreakdown is a breakdown of a portfolio, all balances, and all positions within the portfolio.
 */
export type PortfolioBreakdown = {
  portfolio?: Portfolio;
  portfolioBalances?: PortfolioBalances;
  spotPositions?: Array<PortfolioPosition>;
  perpPositions?: Array<PerpPosition>;
  futuresPositions?: Array<FuturesPosition>;
};
