/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { PortfolioLiquidationStatus } from './enums/PortfolioLiquidationStatus';
import { PortfolioMarginFlags } from './enums/PortfolioMarginFlags';
import { PortfolioMarginType } from './enums/PortfolioMarginType';
import { Amount } from './Amount';

export type Portfolio = {
  /**
   * The portfolio UUID.
   */
  portfolioUuid?: string;
  /**
   * The total collateral value in USDC for the portfolio
   */
  collateral?: string;
  /**
   * The total position notional value in USDC for all positions in the portfolio
   */
  positionNotional?: string;
  /**
   * The total position notional value in USDC for all open orders and positions
   */
  openPositionNotional?: string;
  /**
   * The accrued fees that has not been paid yet in USDC
   */
  pendingFees?: string;
  /**
   * Total borrow amount in USDC (nets the USDC balance, position PNL, held USDC, accrued interest and rolling debt)
   */
  borrow?: string;
  /**
   * Interest charged for borrowed USDC balances
   */
  accruedInterest?: string;
  /**
   * Amount of settled transactions that hasn\'t been paid
   */
  rollingDebt?: string;
  /**
   * The weighted average of all the position\'s initial margin utilization
   */
  portfolioInitialMargin?: string;
  portfolioImNotional?: Amount;
  /**
   * The maintenance margin of the portfolio
   */
  portfolioMaintenanceMargin?: string;
  portfolioMmNotional?: Amount;
  /**
   * The liquidation percentage of the portfolio
   */
  liquidationPercentage?: string;
  /**
   * The liquidation buffer of the portfolio
   */
  liquidationBuffer?: string;
  marginType?: PortfolioMarginType;
  marginFlags?: PortfolioMarginFlags;
  liquidationStatus?: PortfolioLiquidationStatus;
  unrealizedPnl?: Amount;
  totalBalance?: Amount;
};
