/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { PortfolioMarginType } from './enums/PortfolioMarginType';
import { PositionSide } from './enums/PositionSide';
import { Amount } from './Amount';

export type Position = {
  /**
   * The unique identifier of the instrument the position is in.
   */
  productId?: string;
  /**
   * The unique identifier of the instrument the position is in.
   */
  productUuid?: string;
  /**
   * The portfolio UUID.
   */
  portfolioUuid?: string;
  /**
   * The trading pair (e.g. \'BTC-PERP-INTX\').
   */
  symbol?: string;
  vwap?: Amount;
  entryVwap?: Amount;
  positionSide?: PositionSide;
  marginType?: PortfolioMarginType;
  /**
   * The size of the position with positive values reflecting a long position and negative values reflecting a short position.
   */
  netSize?: string;
  /**
   * Cumulative size of all the open buy orders
   */
  buyOrderSize?: string;
  /**
   * Cumulative size of all the open sell orders
   */
  sellOrderSize?: string;
  /**
   * The amount this position contributes to the initial margin
   */
  imContribution?: string;
  unrealizedPnl?: Amount;
  markPrice?: Amount;
  liquidationPrice?: Amount;
  /**
   * The leverage of this position
   */
  leverage?: string;
  imNotional?: Amount;
  mmNotional?: Amount;
  positionNotional?: Amount;
  aggregatedPnl?: Amount;
};
