/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type TwapLimitGtd = {
  /**
   * The amount of the second Asset in the Trading Pair. For example, on the BTC/USD Order Book, USD is the Quote Asset.
   */
  quoteSize?: string;
  /**
   * The amount of the first Asset in the Trading Pair. For example, on the BTC-USD Order Book, BTC is the Base Asset.
   */
  baseSize?: string;
  /**
   * Time at which the order should begin executing.
   */
  startTime?: string;
  /**
   * The time at which the order will be cancelled if it is not Filled.
   */
  endTime?: string;
  /**
   * The specified price, or better, that the Order should be executed at. A Buy Order will execute at or lower than the limit price. A Sell Order will execute at or higher than the limit price.
   */
  limitPrice?: string;
  /**
   * The number of smaller buckets/suborders over which the entire order will be broken into. Each suborder will be executed over a duration calculated based on the end_time
   */
  numberBuckets?: string;
  /**
   * The size of each suborder. bucket_size multiplied by number_buckets should match the size of the entire twap order)
   */
  bucketSize?: string;
  /**
   * The duration over which each sub order was executed
   */
  bucketDuration?: string;
};
