/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ZenginV2Account } from './ZenginV2Account';
import { ZenginV2Institution } from './ZenginV2Institution';

/**
 * For withdrawals: contains all info to initiate payment to a Zengin eligible bank account (non-MUFG). For deposits: contains info to initiate payment to a Coinbase Fiat account.
 */
export type ZenginV2 = {
  accountHolder?: ZenginV2Account;
  institution?: ZenginV2Institution;
};
