/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CancelOrderFailureReason {
  UnknownCancelFailureReason = 'UNKNOWN_CANCEL_FAILURE_REASON',
  InvalidCancelRequest = 'INVALID_CANCEL_REQUEST',
  UnknownCancelOrder = 'UNKNOWN_CANCEL_ORDER',
  CommanderRejectedCancelOrder = 'COMMANDER_REJECTED_CANCEL_ORDER',
  DuplicateCancelRequest = 'DUPLICATE_CANCEL_REQUEST',
  InvalidCancelProductId = 'INVALID_CANCEL_PRODUCT_ID',
  InvalidCancelFcmTradingSession = 'INVALID_CANCEL_FCM_TRADING_SESSION',
  NotAllowedToCancel = 'NOT_ALLOWED_TO_CANCEL',
  OrderIsFullyFilled = 'ORDER_IS_FULLY_FILLED',
  OrderIsBeingReplaced = 'ORDER_IS_BEING_REPLACED',
}
