/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 *
 */
export enum ErrorCodes {
  ErrorCodesUnspecified = 'ERROR_CODES_UNSPECIFIED',
  ErrorCodesAuthenticationError = 'ERROR_CODES_AUTHENTICATION_ERROR',
  ErrorCodesPermissionDenied = 'ERROR_CODES_PERMISSION_DENIED',
  ErrorCodesNotFound = 'ERROR_CODES_NOT_FOUND',
  ErrorCodesInternalServerError = 'ERROR_CODES_INTERNAL_SERVER_ERROR',
  ErrorCodesServiceUnavailable = 'ERROR_CODES_SERVICE_UNAVAILABLE',
  ErrorCodesInvalid = 'ERROR_CODES_INVALID',
  ErrorCodesRejected = 'ERROR_CODES_REJECTED',
  ErrorCodesLimitError = 'ERROR_CODES_LIMIT_ERROR',
  ErrorCodesLimitErrorIncreaseEligible = 'ERROR_CODES_LIMIT_ERROR_INCREASE_ELIGIBLE',
  HighRiskScoreCanceled = 'HIGH_RISK_SCORE_CANCELED',
  ErrorCodesDepositCheckQuestionnaireRequired = 'ERROR_CODES_DEPOSIT_CHECK_QUESTIONNAIRE_REQUIRED',
  ErrorCodesDepositCheckFacematchRequired = 'ERROR_CODES_DEPOSIT_CHECK_FACEMATCH_REQUIRED',
  ErrorCodesDepositCheckFacematchAndQuestionnaireRequired = 'ERROR_CODES_DEPOSIT_CHECK_FACEMATCH_AND_QUESTIONNAIRE_REQUIRED',
  ErrorCodesInsufficientBalance = 'ERROR_CODES_INSUFFICIENT_BALANCE',
  ErrorCodesRateLimited = 'ERROR_CODES_RATE_LIMITED',
  ErrorCodesAddressMismatch = 'ERROR_CODES_ADDRESS_MISMATCH',
  ErrorCodesTransactionNotAllowed = 'ERROR_CODES_TRANSACTION_NOT_ALLOWED',
  DepositNotAuthorized = 'DEPOSIT_NOT_AUTHORIZED',
  PlaidInsufficientFunds = 'PLAID_INSUFFICIENT_FUNDS',
  ErrorCodesLimitErrorIdvMissing = 'ERROR_CODES_LIMIT_ERROR_IDV_MISSING',
  ErrorCodesPaymentRejectedByProvider = 'ERROR_CODES_PAYMENT_REJECTED_BY_PROVIDER',
  ErrorCodesMissing3DsAuthentication = 'ERROR_CODES_MISSING_3DS_AUTHENTICATION',
  ErrorCodesAuthOrWithdrawalLimit = 'ERROR_CODES_AUTH_OR_WITHDRAWAL_LIMIT',
}
