/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum FedwireInstitutionType {
  ChipsIdentifier = 'CHIPS_IDENTIFIER',
  ChipsParticipant = 'CHIPS_PARTICIPANT',
  Dda = 'DDA',
  Fedwire = 'FEDWIRE',
  SwiftBic = 'SWIFT_BIC',
  SwiftBicOrBeiAndAccount = 'SWIFT_BIC_OR_BEI_AND_ACCOUNT',
  PassportNumber = 'PASSPORT_NUMBER',
  TaxIdentificationNumber = 'TAX_IDENTIFICATION_NUMBER',
  DriversLicenseNumber = 'DRIVERS_LICENSE_NUMBER',
  AlienRegistrationNumber = 'ALIEN_REGISTRATION_NUMBER',
  CorporateIdentificationNumber = 'CORPORATE_IDENTIFICATION_NUMBER',
  OtherIdentification = 'OTHER_IDENTIFICATION',
  Unknown = 'UNKNOWN',
}
