/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum NewOrderFailureReason {
  UnknownFailureReason = 'UNKNOWN_FAILURE_REASON',
  UnsupportedOrderConfiguration = 'UNSUPPORTED_ORDER_CONFIGURATION',
  InvalidSide = 'INVALID_SIDE',
  InvalidProductId = 'INVALID_PRODUCT_ID',
  InvalidSizePrecision = 'INVALID_SIZE_PRECISION',
  InvalidPricePrecision = 'INVALID_PRICE_PRECISION',
  InsufficientFund = 'INSUFFICIENT_FUND',
  InvalidLedgerBalance = 'INVALID_LEDGER_BALANCE',
  OrderEntryDisabled = 'ORDER_ENTRY_DISABLED',
  IneligiblePair = 'INELIGIBLE_PAIR',
  InvalidLimitPricePostOnly = 'INVALID_LIMIT_PRICE_POST_ONLY',
  InvalidLimitPrice = 'INVALID_LIMIT_PRICE',
  InvalidNoLiquidity = 'INVALID_NO_LIQUIDITY',
  InvalidRequest = 'INVALID_REQUEST',
  CommanderRejectedNewOrder = 'COMMANDER_REJECTED_NEW_ORDER',
  InsufficientFunds = 'INSUFFICIENT_FUNDS',
  InLiquidation = 'IN_LIQUIDATION',
  InvalidMarginType = 'INVALID_MARGIN_TYPE',
  InvalidLeverage = 'INVALID_LEVERAGE',
  UntradableProduct = 'UNTRADABLE_PRODUCT',
  InvalidFcmTradingSession = 'INVALID_FCM_TRADING_SESSION',
  GeofencingRestriction = 'GEOFENCING_RESTRICTION',
  QuoteSizeNotAllowedForBracket = 'QUOTE_SIZE_NOT_ALLOWED_FOR_BRACKET',
  InvalidBracketPrices = 'INVALID_BRACKET_PRICES',
  MissingMarketTradeData = 'MISSING_MARKET_TRADE_DATA',
  InvalidBracketLimitPrice = 'INVALID_BRACKET_LIMIT_PRICE',
  InvalidBracketStopTriggerPrice = 'INVALID_BRACKET_STOP_TRIGGER_PRICE',
  BracketLimitPriceOutOfBounds = 'BRACKET_LIMIT_PRICE_OUT_OF_BOUNDS',
  StopTriggerPriceOutOfBounds = 'STOP_TRIGGER_PRICE_OUT_OF_BOUNDS',
  BracketOrderNotSupported = 'BRACKET_ORDER_NOT_SUPPORTED',
  FokDisabled = 'FOK_DISABLED',
  FokOnlyAllowedOnLimitOrders = 'FOK_ONLY_ALLOWED_ON_LIMIT_ORDERS',
  PostOnlyNotAllowedWithFok = 'POST_ONLY_NOT_ALLOWED_WITH_FOK',
  UboHighLeverageQuantityBreached = 'UBO_HIGH_LEVERAGE_QUANTITY_BREACHED',
  EndTimeTooFarInFuture = 'END_TIME_TOO_FAR_IN_FUTURE',
  LimitPriceTooFarFromMarket = 'LIMIT_PRICE_TOO_FAR_FROM_MARKET',
  OpenBracketOrders = 'OPEN_BRACKET_ORDERS',
  FuturesAfterHourInvalidOrderType = 'FUTURES_AFTER_HOUR_INVALID_ORDER_TYPE',
  FuturesAfterHourInvalidTimeInForce = 'FUTURES_AFTER_HOUR_INVALID_TIME_IN_FORCE',
  InvalidAttachedTakeProfitPrice = 'INVALID_ATTACHED_TAKE_PROFIT_PRICE',
  InvalidAttachedStopLossPrice = 'INVALID_ATTACHED_STOP_LOSS_PRICE',
  InvalidAttachedTakeProfitPricePrecision = 'INVALID_ATTACHED_TAKE_PROFIT_PRICE_PRECISION',
  InvalidAttachedStopLossPricePrecision = 'INVALID_ATTACHED_STOP_LOSS_PRICE_PRECISION',
  InvalidAttachedTakeProfitPriceOutOfBounds = 'INVALID_ATTACHED_TAKE_PROFIT_PRICE_OUT_OF_BOUNDS',
  InvalidAttachedStopLossPriceOutOfBounds = 'INVALID_ATTACHED_STOP_LOSS_PRICE_OUT_OF_BOUNDS',
  InvalidAttachedTakeProfitPriceExceedsMaxDistanceFromOriginatingPrice = 'INVALID_ATTACHED_TAKE_PROFIT_PRICE_EXCEEDS_MAX_DISTANCE_FROM_ORIGINATING_PRICE',
  InvalidAttachedTakeProfitSizeBelowMin = 'INVALID_ATTACHED_TAKE_PROFIT_SIZE_BELOW_MIN',
  AttachedOrderSizeMustBeNil = 'ATTACHED_ORDER_SIZE_MUST_BE_NIL',
}
