/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum PaymentMethodType {
  Invalid = 'INVALID',
  Unset = 'UNSET',
  BlockchainAddress = 'BLOCKCHAIN_ADDRESS',
  CoinbaseAccount = 'COINBASE_ACCOUNT',
  BlockchainTransaction = 'BLOCKCHAIN_TRANSACTION',
  Fedwire = 'FEDWIRE',
  Swift = 'SWIFT',
  Card = 'CARD',
  Zengin = 'ZENGIN',
  Uk = 'UK',
  Sepa = 'SEPA',
  Paypal = 'PAYPAL',
  LedgerAccount = 'LEDGER_ACCOUNT',
  ExternalPaymentMethod = 'EXTERNAL_PAYMENT_METHOD',
  ProAccount = 'PRO_ACCOUNT',
  Rtp = 'RTP',
  CardRepresentment = 'CARD_REPRESENTMENT',
  Venue = 'VENUE',
  LedgerNamedAccount = 'LEDGER_NAMED_ACCOUNT',
  CustodialPool = 'CUSTODIAL_POOL',
  ApplePay = 'APPLE_PAY',
  DefaultAccount = 'DEFAULT_ACCOUNT',
  Remitly = 'REMITLY',
  ProInternalAccount = 'PRO_INTERNAL_ACCOUNT',
  DappWalletAccount = 'DAPP_WALLET_ACCOUNT',
  GooglePay = 'GOOGLE_PAY',
  DappWalletBlockchainAddress = 'DAPP_WALLET_BLOCKCHAIN_ADDRESS',
  ZaakpayMobikwik = 'ZAAKPAY_MOBIKWIK',
  DenebUpi = 'DENEB_UPI',
  BankAccount = 'BANK_ACCOUNT',
  IdentityContractCall = 'IDENTITY_CONTRACT_CALL',
  DenebImps = 'DENEB_IMPS',
  Allocation = 'ALLOCATION',
  LiquidityPool = 'LIQUIDITY_POOL',
  ZenginV2 = 'ZENGIN_V2',
  DirectDeposit = 'DIRECT_DEPOSIT',
  SepaV2 = 'SEPA_V2',
  Zepto = 'ZEPTO',
  PixEbanx = 'PIX_EBANX',
  Signet = 'SIGNET',
  DerivativeSettlement = 'DERIVATIVE_SETTLEMENT',
  User = 'USER',
  SgFast = 'SG_FAST',
  Interac = 'INTERAC',
  IntraBank = 'INTRA_BANK',
  Cbit = 'CBIT',
  Ideal = 'IDEAL',
  Sofort = 'SOFORT',
  SgPaynow = 'SG_PAYNOW',
  CheckoutPaymentLink = 'CHECKOUT_PAYMENT_LINK',
  EmailAddress = 'EMAIL_ADDRESS',
  PhoneNumber = 'PHONE_NUMBER',
  VendorPayment = 'VENDOR_PAYMENT',
  Ctn = 'CTN',
  BancomatPay = 'BANCOMAT_PAY',
  HotWallet = 'HOT_WALLET',
  NovaAccount = 'NOVA_ACCOUNT',
  MagicSpendBlockchainAddress = 'MAGIC_SPEND_BLOCKCHAIN_ADDRESS',
  TransferPointer = 'TRANSFER_POINTER',
  Eft = 'EFT',
  WallaceAccount = 'WALLACE_ACCOUNT',
  Manual = 'MANUAL',
  ArgentineBankAccount = 'ARGENTINE_BANK_ACCOUNT',
  Representment = 'REPRESENTMENT',
  BankingCircleNow = 'BANKING_CIRCLE_NOW',
  Trustly = 'TRUSTLY',
  Blik = 'BLIK',
  MbWay = 'MB_WAY',
  Pix = 'PIX',
}
