/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum PreviewFailureReason {
  UnknownPreviewFailureReason = 'UNKNOWN_PREVIEW_FAILURE_REASON',
  PreviewMissingCommissionRate = 'PREVIEW_MISSING_COMMISSION_RATE',
  PreviewInvalidSide = 'PREVIEW_INVALID_SIDE',
  PreviewInvalidOrderConfig = 'PREVIEW_INVALID_ORDER_CONFIG',
  PreviewInvalidProductId = 'PREVIEW_INVALID_PRODUCT_ID',
  PreviewInvalidSizePrecision = 'PREVIEW_INVALID_SIZE_PRECISION',
  PreviewInvalidPricePrecision = 'PREVIEW_INVALID_PRICE_PRECISION',
  PreviewMissingProductPriceBook = 'PREVIEW_MISSING_PRODUCT_PRICE_BOOK',
  PreviewInvalidLedgerBalance = 'PREVIEW_INVALID_LEDGER_BALANCE',
  PreviewInsufficientLedgerBalance = 'PREVIEW_INSUFFICIENT_LEDGER_BALANCE',
  PreviewInvalidLimitPricePostOnly = 'PREVIEW_INVALID_LIMIT_PRICE_POST_ONLY',
  PreviewInvalidLimitPrice = 'PREVIEW_INVALID_LIMIT_PRICE',
  PreviewInvalidNoLiquidity = 'PREVIEW_INVALID_NO_LIQUIDITY',
  PreviewInsufficientFund = 'PREVIEW_INSUFFICIENT_FUND',
  PreviewInvalidCommissionConfiguration = 'PREVIEW_INVALID_COMMISSION_CONFIGURATION',
  PreviewInvalidStopPrice = 'PREVIEW_INVALID_STOP_PRICE',
  PreviewInvalidBaseSizeTooLarge = 'PREVIEW_INVALID_BASE_SIZE_TOO_LARGE',
  PreviewInvalidBaseSizeTooSmall = 'PREVIEW_INVALID_BASE_SIZE_TOO_SMALL',
  PreviewInvalidQuoteSizePrecision = 'PREVIEW_INVALID_QUOTE_SIZE_PRECISION',
  PreviewInvalidQuoteSizeTooLarge = 'PREVIEW_INVALID_QUOTE_SIZE_TOO_LARGE',
  PreviewInvalidPriceTooLarge = 'PREVIEW_INVALID_PRICE_TOO_LARGE',
  PreviewInvalidQuoteSizeTooSmall = 'PREVIEW_INVALID_QUOTE_SIZE_TOO_SMALL',
  PreviewInsufficientFundsForFutures = 'PREVIEW_INSUFFICIENT_FUNDS_FOR_FUTURES',
  PreviewBreachedPriceLimit = 'PREVIEW_BREACHED_PRICE_LIMIT',
  PreviewBreachedAccountPositionLimit = 'PREVIEW_BREACHED_ACCOUNT_POSITION_LIMIT',
  PreviewBreachedCompanyPositionLimit = 'PREVIEW_BREACHED_COMPANY_POSITION_LIMIT',
  PreviewInvalidMarginHealth = 'PREVIEW_INVALID_MARGIN_HEALTH',
  PreviewRiskProxyFailure = 'PREVIEW_RISK_PROXY_FAILURE',
  PreviewUntradableFcmAccountStatus = 'PREVIEW_UNTRADABLE_FCM_ACCOUNT_STATUS',
  PreviewInLiquidation = 'PREVIEW_IN_LIQUIDATION',
  PreviewInvalidMarginType = 'PREVIEW_INVALID_MARGIN_TYPE',
  PreviewInvalidLeverage = 'PREVIEW_INVALID_LEVERAGE',
  PreviewUntradableProduct = 'PREVIEW_UNTRADABLE_PRODUCT',
  PreviewInvalidFcmTradingSession = 'PREVIEW_INVALID_FCM_TRADING_SESSION',
  PreviewNotAllowedByMarketState = 'PREVIEW_NOT_ALLOWED_BY_MARKET_STATE',
  PreviewBreachedOpenInterestLimit = 'PREVIEW_BREACHED_OPEN_INTEREST_LIMIT',
  PreviewGeofencingRestriction = 'PREVIEW_GEOFENCING_RESTRICTION',
  PreviewInvalidEndTime = 'PREVIEW_INVALID_END_TIME',
  PreviewOppositeMarginTypeExists = 'PREVIEW_OPPOSITE_MARGIN_TYPE_EXISTS',
  PreviewQuoteSizeNotAllowedForBracket = 'PREVIEW_QUOTE_SIZE_NOT_ALLOWED_FOR_BRACKET',
  PreviewInvalidBracketPrices = 'PREVIEW_INVALID_BRACKET_PRICES',
  PreviewMissingMarketTradeData = 'PREVIEW_MISSING_MARKET_TRADE_DATA',
  PreviewInvalidBracketLimitPrice = 'PREVIEW_INVALID_BRACKET_LIMIT_PRICE',
  PreviewInvalidBracketStopTriggerPrice = 'PREVIEW_INVALID_BRACKET_STOP_TRIGGER_PRICE',
  PreviewBracketLimitPriceOutOfBounds = 'PREVIEW_BRACKET_LIMIT_PRICE_OUT_OF_BOUNDS',
  PreviewStopTriggerPriceOutOfBounds = 'PREVIEW_STOP_TRIGGER_PRICE_OUT_OF_BOUNDS',
  PreviewBracketOrderNotSupported = 'PREVIEW_BRACKET_ORDER_NOT_SUPPORTED',
  PreviewInvalidStopPricePrecision = 'PREVIEW_INVALID_STOP_PRICE_PRECISION',
  PreviewStopPriceAboveLimitPrice = 'PREVIEW_STOP_PRICE_ABOVE_LIMIT_PRICE',
  PreviewStopPriceBelowLimitPrice = 'PREVIEW_STOP_PRICE_BELOW_LIMIT_PRICE',
  PreviewStopPriceAboveLastTradePrice = 'PREVIEW_STOP_PRICE_ABOVE_LAST_TRADE_PRICE',
  PreviewStopPriceBelowLastTradePrice = 'PREVIEW_STOP_PRICE_BELOW_LAST_TRADE_PRICE',
  PreviewFokDisabled = 'PREVIEW_FOK_DISABLED',
  PreviewFokOnlyAllowedOnLimitOrders = 'PREVIEW_FOK_ONLY_ALLOWED_ON_LIMIT_ORDERS',
  PreviewPostOnlyNotAllowedWithFok = 'PREVIEW_POST_ONLY_NOT_ALLOWED_WITH_FOK',
  PreviewUboHighLeverageQuantityBreached = 'PREVIEW_UBO_HIGH_LEVERAGE_QUANTITY_BREACHED',
  PreviewEcosystemLeverageUtilizationBreached = 'PREVIEW_ECOSYSTEM_LEVERAGE_UTILIZATION_BREACHED',
  PreviewCloseOnlyFailure = 'PREVIEW_CLOSE_ONLY_FAILURE',
  PreviewUboHighLeverageNotionalBreached = 'PREVIEW_UBO_HIGH_LEVERAGE_NOTIONAL_BREACHED',
  PreviewEndTimeTooFarInFuture = 'PREVIEW_END_TIME_TOO_FAR_IN_FUTURE',
  PreviewLimitPriceTooFarFromMarket = 'PREVIEW_LIMIT_PRICE_TOO_FAR_FROM_MARKET',
  PreviewFuturesAfterHourInvalidOrderType = 'PREVIEW_FUTURES_AFTER_HOUR_INVALID_ORDER_TYPE',
  PreviewFuturesAfterHourInvalidTimeInForce = 'PREVIEW_FUTURES_AFTER_HOUR_INVALID_TIME_IN_FORCE',
  PreviewInvalidAttachedTakeProfitPrice = 'PREVIEW_INVALID_ATTACHED_TAKE_PROFIT_PRICE',
  PreviewInvalidAttachedStopLossPrice = 'PREVIEW_INVALID_ATTACHED_STOP_LOSS_PRICE',
  PreviewInvalidAttachedTakeProfitPricePrecision = 'PREVIEW_INVALID_ATTACHED_TAKE_PROFIT_PRICE_PRECISION',
  PreviewInvalidAttachedStopLossPricePrecision = 'PREVIEW_INVALID_ATTACHED_STOP_LOSS_PRICE_PRECISION',
  PreviewInvalidAttachedTakeProfitPriceOutOfBounds = 'PREVIEW_INVALID_ATTACHED_TAKE_PROFIT_PRICE_OUT_OF_BOUNDS',
  PreviewInvalidAttachedStopLossPriceOutOfBounds = 'PREVIEW_INVALID_ATTACHED_STOP_LOSS_PRICE_OUT_OF_BOUNDS',
  PreviewInvalidBracketOrderSide = 'PREVIEW_INVALID_BRACKET_ORDER_SIDE',
  PreviewBracketOrderSizeExceedsPosition = 'PREVIEW_BRACKET_ORDER_SIZE_EXCEEDS_POSITION',
  PreviewOrderSizeExceedsBracketedPosition = 'PREVIEW_ORDER_SIZE_EXCEEDS_BRACKETED_POSITION',
  PreviewInvalidLimitPricePrecision = 'PREVIEW_INVALID_LIMIT_PRICE_PRECISION',
  PreviewInvalidStopTriggerPricePrecision = 'PREVIEW_INVALID_STOP_TRIGGER_PRICE_PRECISION',
  PreviewInvalidAttachedTakeProfitPriceExceedsMaxDistanceFromOriginatingPrice = 'PREVIEW_INVALID_ATTACHED_TAKE_PROFIT_PRICE_EXCEEDS_MAX_DISTANCE_FROM_ORIGINATING_PRICE',
  PreviewInvalidAttachedTakeProfitSizeBelowMin = 'PREVIEW_INVALID_ATTACHED_TAKE_PROFIT_SIZE_BELOW_MIN',
  PreviewAttachedOrderSizeMustBeNil = 'PREVIEW_ATTACHED_ORDER_SIZE_MUST_BE_NIL',
  PreviewBelowMinSizeForDuration = 'PREVIEW_BELOW_MIN_SIZE_FOR_DURATION',
}
